[package]
name = "alamo-movies"
version = "0.1.0"
authors = ["Spike Grobstein <me@spike.cx>"]
edition = "2018"

[[bin]]
name = "adc"
path = "src/main.rs"

[dependencies]
serde_json = "1.0"
lazy_static = "1.2"
regex = "1"
clap = "2.32.0"
reqwest = "0.9.10"
chrono = "0.4.6"
